name: Build with Theos (macOS)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Theos and sdks
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
          echo "PATH=\$PATH:$HOME/theos/bin" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew install perl ldid make dpkg

      - name: Build (rootful)
        env:
          THEOS: ${{ env.THEOS }}
          THEOS_MAKE_PATH: ${{ env.THEOS_MAKE_PATH }}
          THEOS_PLATFORM_SDK_ROOT: $HOME/theos/sdks/iPhoneOS10.3.sdk
          ARCHS: "arm64 armv7"
        run: |
          make clean package
          mkdir -p build/rootful
          mv *.deb build/rootful/ || true

      - name: Build (rootless)
        env:
          THEOS: ${{ env.THEOS }}
          THEOS_MAKE_PATH: ${{ env.THEOS_MAKE_PATH }}
          THEOS_PLATFORM_SDK_ROOT: $HOME/theos/sdks/iPhoneOS15.6.sdk
          THEOS_PACKAGE_SCHEME: rootless
          ARCHS: "arm64 arm64e"
        run: |
          make clean package
          mkdir -p build/rootless
          mv *.deb build/rootless/ || true

      - name: Upload Artifacts (rootful)
        uses: actions/upload-artifact@v4
        with:
          name: rootful-build
          path: build/rootful/*.deb

      - name: Upload Artifacts (rootless)
        uses: actions/upload-artifact@v4
        with:
          name: rootless-build
          path: build/rootless/*.deb
